### ISSUE TITLE
Facebook Login

### ISSUE THREAD

**Issue by Taynewgar** [jahed/map-xenoblade-chronicles-x#3]
Hi

First of all, i have to thank you for all your work on this!!! Everyone can see how much you like the game AND your profession! GRATZ

I tried to login with facebook, but i keep getting the same error, over and over.

Ill attach a screenshot.

Thanks again.
![error](https://cloud.githubusercontent.com/assets/19688267/15711018/af82d254-27e2-11e6-975c-9d070eaf74b1.jpg)

**Comment by jahed** [comment]
Thanks, I was wondering why no one was using Facebook to login. Worked fine for me because I'm the app owner. Turns out there's a poorly visible option to turn it on for production.

Should be fixed now. Can you confirm?

**Comment by Taynewgar** [comment]
Working Now!

THX a Million!!

2016-06-01 18:35 GMT-03:00 Jahed <notifications@github.com>:

> Thanks, I was wondering why no one was using Facebook to login. Worked
> fine for me because I'm the app owner. Turns out there's a poorly visible
> option to turn it on for production.
>
> Should be fixed now. Can you confirm?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jahed/map-xenoblade-chronicles-x/issues/3#issuecomment-223132253>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASxrS0GaqArP2KfgSXa_G7T036Et2guXks5qHfs7gaJpZM4Iribf>
> .
>



-- 
Wagner Martins Rosa
