### ISSUE TITLE
Missing Base Camp

### ISSUE THREAD

**Issue by Webbiasty** [jahed/map-xenoblade-chronicles-x#5]
Hello,
I would like to let you know of a missing Base Camp i found (or rather not):

- Quing Long Glade BC
- bellow Great Nail landmark
- above FN Site 212

I am not sure if that project is still worked on but I figuered I will let you know.
Thanks for your work,
John

**Comment by jahed** [comment]
Thanks for letting me know. I'll add it the next time I get the chance to.

**Comment by jahed** [comment]
Going to keep this open until I've actually got it done.

**Comment by jahed** [comment]
Done!
