### ISSUE TITLE
Slowdowns with Chrome

### ISSUE THREAD

**Issue by ReN3xt** [jahed/map-xenoblade-chronicles-x#6]
Hi @jahed,
this isn't a problem of your application, but I can't understand why it goes very slowly on Google Chrome and smoothly on Mozilla Firefox (and other web browsers). I noticed that this only happens with "Segments" and "Probes" maps.

What could be the problem?
Thank you very much.

**Comment by jahed** [comment]
Strange, I tend to have the opposite issue. Chrome runs way smoother than Firefox on every machine I've tried.

If you can, follow these steps:

1. Go to the Segment or Probe view
2. Open the Developer Tools (`CTRL` + `SHIFT` + `I`)
3. In the Developer Tools, go to the "Console" tab
4. Copy and paste the content of the Console here.

**Comment by ReN3xt** [comment]
`bundle.js?v=756d336:13`
`Pixi.js __VERSION__ - ✰ WebGL ✰      http://www.pixijs.com/    ♥♥♥`

**Comment by jahed** [comment]
So it's using WebGL, thought it might be using Canvas but guess not.

If Firefox is fine, I don't see why Chrome wouldn't be either. Hard to say what's causing it without trying stuff out on your machine.

It's definitely something to do with the WebGL rendering performance. The only other info that might help are:

- Operating System version
- Google Chrome version
- Mozilla Firefox version
- CPU model
- Graphics card model
- Total RAM

You can also try disabling all your plugins/extensions and see if it helps. If it does, it'll mean one of your plugins is interfering.

**Comment by ReN3xt** [comment]
Thanks again for the help, I'm sorry to waste your time.

Anyway here's the information:
- Windows 7
- Chrome: 52.0.2743.116
- Firefox: 48.0
- i5-3570K @ 4.4GHz
- MSI HD 7970 Lightning @ 1200MHz
- 16GB

I tried to disable plugins and extensions, but nothing has changed.
I tried to enable "WebGL 2.0 Prototype" in chrome://flags and now is slightly better, but still slower than Firefox. It could be a WebGL issue?

**Comment by jahed** [comment]
Your computer specs are slightly better than mine...

The only other thing I can recommend is to update your graphics card drivers. Other than that, I have no clue :confused:

But yeah, looks like a WebGL / graphics card issue.

**Comment by ReN3xt** [comment]
I tried a few web applications that use WebGL, and this is the result:

e.g: [webgl_animation_cloth](http://threejs.org/examples/#webgl_animation_cloth)
![](http://i.imgur.com/rsXWEDv.png)

I don't think it's a hardware problem, but a WebGL issue on Google Chrome.
I know we're off topic now, but do you have any advice? Otherwise you can close this issue.

Thank you!

**Comment by ReN3xt** [comment]
Ok, I found a solution. I had to enable #ignore-gpu-blacklist in chrome://flags. Probably my GPU is blacklisted and the hardware acceleration (and consequently WebGL) on Google Chrome wasn't working properly.

I'm sorry I wasted your time, this issue can be closed.

**Comment by jahed** [comment]
No problem, glad you got it solved!
