### ISSUE TITLE
Missing Segment

### ISSUE THREAD

**Issue by Webbiasty** [jahed/map-xenoblade-chronicles-x#7]
Hello again,
Missing Segment:
- Oblivia,
- south-east of FN Site 319,
- Unexplored Territory Great Washington Isle,
- Mechanical Level 4,

Thanks for your work,
John

**Comment by jahed** [comment]
I don't have my WiiU setup at the moment. Is it also a Fast Travel segment?

**Comment by jahed** [comment]
Found a screenshot showing it's not fast travel.

Done.
