### ISSUE TITLE
Level Filtering

### ISSUE THREAD

**Issue by Lysenthia** [jahed/map-xenoblade-chronicles-x#8]
Hey @jahed,
Thanks for making this. It's ridiculously awesome.
I was wondering if you would be able to add some way to filter the list of enemies to show enemies between certain levels.
Thanks!

**Comment by jahed** [comment]
Great idea and pretty straight forward to do. Done!

![xmap49](https://cloud.githubusercontent.com/assets/3330963/18231173/38261eac-72a9-11e6-9c53-e1b9bed9695f.gif)
